sudo: false
language: java

notifications:
  webhooks:
    urls:
      -  https://webhooks.gitter.im/e/8ad3ceb23385ac884d39
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
